"""
Update existing Docusaurus site with Claude-generated onboarding doc
Usage: python update_site.py <repo_path> <repo_name> [site_path]
"""

import json
import subprocess
import sys
import requests
from pathlib import Path

def run_scanner(repo_path, output_dir="outputs"):
    """Generate scan.jsonl"""
    print("🔍 Scanning repository...")

    Path(output_dir).mkdir(exist_ok=True)

    cmd = [
            "python", "cli/main.py",
            "--repo", repo_path,
            "--format", "jsonl",
            "--out", f"{output_dir}/scan.jsonl"
    ]

    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        print(f"🚨 Scanner failed: {result.stderr}")
        return False

    print(f"✅ Generated {output_dir}/scan.jsonl")
    return True

def generate_onboarding_doc(scan_file, repo_name):
    """Call Claude API"""
    print("🤖 Generating onboarding doc with Claude...")

    try:
        repo_data = Path(scan_file).read_text()

        payload = {
                "repo_data": repo_data,
                "repo_name": repo_name,
        }

        response = requests.post(
                "https://vd03y9yw0g.execute-api.us-east-1.amazonaws.com/prod/chat",
                headers={"Content-Type": "application/json"},
                json=payload,
                timeout=60
        )

        if response.status_code == 200:
            result = response.json()
            print("✅ Onboarding doc generated")
            return result.get("onboarding_doc", "")
        else:
            print(f"❌ Claude API failed: {response.status_code}")
            print(response.text)
            return None

    except Exception as e:
        print(f"❌ Error: {e}")
        return None

def update_existing_site(onboarding_doc, repo_name, site_path):
    """Update existing Docusaurus site"""
    print("📝 Updating Docusaurus site...")

    site_dir = Path(site_path)
    if not site_dir.exists():
        print(f"❌ Site directory {site_path} not found")
        return False

    # Create intro.md
    intro_content = f"""---
sidebar_position: 1
---

# {repo_name} - Architecture Overview

{onboarding_doc}

---

*This documentation was automatically generated by Ghost Onboarder using Claude AI.*
"""

    # Update docs/intro.md
    docs_path = site_dir / "docs" / "intro.md"
    docs_path.parent.mkdir(exist_ok=True)
    docs_path.write_text(intro_content)

    print(f"✅ Updated {docs_path}")

    # Update title in docusaurus.config.ts if it exists
    config_path = site_dir / "docusaurus.config.ts"
    if config_path.exists():
        config_content = config_path.read_text()
        if "title: 'Ghost Onboarder'," in config_content:
            updated_config = config_content.replace(
                "title: 'Ghost Onboarder',",
                f"title: '{repo_name} Documentation',"
            ).replace(
                "tagline: 'Turn any repo into a self-explaining codebase',",
                f"tagline: 'Auto-generated documentation for {repo_name}',"
            )
            config_path.write_text(updated_config)
            print(f"✅ Updated site title")

    return True

def main():
    if len(sys.argv) < 3:
        print("Usage: python update_site.py <repo_path> <repo_name> [site_path]")
        print("Example: python update_site.py ../tmprepo/modern-portfolio akashbagchi/modern-portfolio ghost-onboarder-site")
        sys.exit(1)

    repo_path = sys.argv[1]
    repo_name = sys.argv[2]
    site_path = sys.argv[3] if len(sys.argv) > 3 else "ghost-onboarder-site"

    print(f"🏁 Updating {site_path} with docs for {repo_name}")
    print()

    # Step 1: Generate scan
    if not run_scanner(repo_path):
        sys.exit(1)

    # Step 2: Generate docs
    onboarding_doc = generate_onboarding_doc("outputs/scan.jsonl", repo_name)
    if not onboarding_doc:
        sys.exit(1)

    # Step 3: Update site
    if not update_existing_site(onboarding_doc, repo_name, site_path):
        sys.exit(1)

    print()
    print("🎉 Site updated successfully!")
    print(f"💡 Start site: cd {site_path} && npm start")

if __name__ == "__main__":
    main()

